name: sqlite-connect

logging:
  level:
    .: debug
    org.springframework: DEBUG
  file:
    name: ${HOME}/logs/sqlite-connect.log

app:
  name: ${name}
  db-name: sqlitedb.sqlite
  db-username: sa
  db-password: sa
  db-url-prefix: jdbc:sqlite

spring:
  datasource:
    username: ${app.db-username}
    password: ${app.db-password}
    driver-class-name: org.sqlite.JDBC
    url: ${app.db-url-prefix}:${app.db-name}
